### ISSUE TITLE
Play 2.5.9 Error

### ISSUE THREAD

**Issue by hendisantika** [lloydmeta/metascraper-service#2]
I used Play 2.5.9 and got Error.

How do I solve the issue?

Thanks

**Comment by lloydmeta** [comment]
Hi there, 

This project hasn't been touched in over 3 years and some dependencies are out of date.  If you want to use the latest version of Play, you'll need to resolve the compile issues one at a time.  If you have time to put together a PR, I'd be more than happy to merge it !

Lloyd

**Comment by hendisantika** [comment]
Ooo ... I can see that.

OK. 
Maybe I will have some pull request (PR) from yours.
Thanks.
